meta_product_name: "EZ-Contract"
meta_title: "Signing made easy"
meta_description: "Use EZ-Contract to sign your contracts and never lose them again"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
